{% set name = "plant-isce3" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/plant-isce3/archive/v{{ version }}.tar.gz
  sha256: 8694794b4892ec3ccd0785fa7e3ea6bbf789fb1e21223c3c3a13291f9216ef72

build:
  entry_points:
    - plant_isce3_info = plant_isce3.plant_isce3_info:main_cli
    - plant_isce3_geocode = plant_isce3.plant_isce3_geocode:main_cli
    - plant_isce3_polygon = plant_isce3.plant_isce3_polygon:main_cli
    - plant_isce3_topo = plant_isce3.plant_isce3_topo:main_cli
    - plant_isce3_util = plant_isce3.plant_isce3_util:main_cli
    - plant_isce3_filter = plant_isce3.plant_isce3_filter:main_cli
    - plant_isce3_rtc = plant_isce3.plant_isce3_rtc:main_cli
    - plant_isce3_resample = plant_isce3.plant_isce3_resample:main_cli
    - plant_isce3_runconfig = plant_isce3.plant_isce3_runconfig:main_cli
    - plant_isce3_batch_processing = plant_isce3.plant_isce3_batch_processing:main_cli
    - plant_isce3_rslc_eap_analysis = plant_isce3.plant_isce3_rslc_eap_analysis:main_cli
    - plant_isce3_off_diagonal_analysis = plant_isce3.plant_isce3_off_diagonal_analysis:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.25.2
    - gdal ==3.11.4
    - isce3 >=0.25.3
    - plant >=0.8.4
    - libnetcdf
    - h5py
    - matplotlib-base
    - scipy
    - s1reader >=0.2.5
    - boto3
    - geopandas
    - shapely
    - libgdal-hdf5
    - libgdal-netcdf
    - pyre >=1.12.5

test:
  imports:
    - plant_isce3
  commands:
    - plant_isce3_info --help
    - plant_isce3_geocode --help
    - plant_isce3_polygon --help
    - plant_isce3_topo --help
    - plant_isce3_util --help
    - plant_isce3_filter --help
    - plant_isce3_rtc --help
    - plant_isce3_resample --help
    - plant_isce3_runconfig --help
    - plant_isce3_batch_processing --help
    - plant_isce3_rslc_eap_analysis --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/isce-framework/plant-isce3
  summary: 'PLAnT-ISCE3: Polarimetric Interferometric Lab and Analysis Tool (PLAnT) scripts for the InSAR Scientific Computing Environment 3 (ISCE3)'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gshiroma
